### ISSUE TITLE
Correct Multiset Calculation

### ISSUE THREAD

**Issue by pmbaumgartner** [benedekrozemberczki/graph2vec#11]
Thanks for your work on this library. I was looking through the code after I applied this to my own dataset and noticed a potential issue with the calculation of the label multiset in the WeisfeilerLehmanMachine.

In the [original paper](https://people.mpi-inf.mpg.de/~mehlhorn/ftp/genWLpaper.pdf) they provide this figure to explain one iteration of the relabeling process(p. 10): 
<img width="780" alt="Screen Shot 2019-07-28 at 2 12 43 PM" src="https://user-images.githubusercontent.com/5107405/62011148-9064e500-b142-11e9-8067-32678cea8278.png">

In particular, the node with label `4` in the left graph has a pre-hashed label of `4,1135` - meaning it's original label is `4`, and the multiset representation of its neighbors labels is `1135`

I think there's an issue in how this multiset is calculated in the `WeisfeilerLehmanMachine` class, specifically this line: https://github.com/benedekrozemberczki/graph2vec/blob/master/src/graph2vec.py#L42 
 
I've got a simple reproduction of this logic here. I am expecting the output to be `4_1_1_3_5`, however, I get:

```python
>>> node_label = "4"
>>> neighbor_labels = ["5", "3", "1", "1"]
>>> features = "_".join([node_label] + list(set(sorted([str(n) for n in neighbor_labels]))))
>>> print(features)
4_5_1_3
```

I believe you can fix this by removing the creation of the set, I'm not sure that's doing what we want. Since sets are [unordered collections of objects](https://docs.python.org/3.7/library/stdtypes.html#set-types-set-frozenset), we are effectively ordering the objects with `sorted` and then unordering them with `set`.

I could be wrong as I didn't evaluate the full pipliene here - there maybe some other change in the input to this function that does give you the correct answer, but I think this part of the implementation is worth another look.

**Comment by benedekrozemberczki** [comment]
Modified.
