### ISSUE TITLE
How about training an undirected weighted graph?

### ISSUE THREAD

**Issue by hl-henry** [benedekrozemberczki/graph2vec#12]
How about training an undirected weighted graph? How should I modify the code and input?
And How about dynamic graph input?

**Comment by benedekrozemberczki** [comment]
This is not a node embedding technique.

**Comment by ZiruiYan** [comment]
The code can easily run on an undirected graph using networkx and the result can be expected, but may can be difficult to handle edge weights.

**Comment by benedekrozemberczki** [comment]
It is out of scope of the original paper.
