### ISSUE TITLE
Error for new dataset: RuntimeError: you must first build vocabulary before training the model

### ISSUE THREAD

**Issue by BehroozMansouri** [benedekrozemberczki/graph2vec#13]
When changing the dataset to new one with the format of the test dataset, I get the following error:
RuntimeError: you must first build vocabulary before training the model.

Where should I specify the vocabulary and where should it be located?

**Comment by benedekrozemberczki** [comment]
Can you show me samples of your data?

**Comment by ZiruiYan** [comment]
This is most likely because the amount of data is too small and all features are deleted.

**Comment by bistuwyylearning** [comment]
直接在src目录下执行python graph2vec.py就会导致整个错误
正确的做法是在graph2vec主目录直接执行python src/graph2vec.py
