### ISSUE TITLE
multiple features

### ISSUE THREAD

**Issue by Beattion** [benedekrozemberczki/graph2vec#16]
If each node has many features instead of one, for example , {"edges": [[0, 1], [0, 2]], "features": {"0": "7,3,4", "1": "8,3,5", "2": "9,2,7"}} , how can I represent the dataset as input?  Thank you.

**Comment by benedekrozemberczki** [comment]
You can create for each feature a separate WL hashing.

**Comment by sbhttchryy** [comment]
Hello, this is just to confirm regarding this issue. If a node has 2 features f1 and f2, after creating the hashing for both the features, how should the hash table look like? Just the node as key and the sum of the hashes of the features f1 and f2?

**Comment by HodaMemar** [comment]
Hi,
This is also my question.

**Comment by benedekrozemberczki** [comment]
Yes. But you could be smarter by executing the wl algorithm for each
feature separately. That would have a O(|e|* # features * # hashes)
complexity. This way you would describe the distributional characteristics
for each feature.
.
