### ISSUE TITLE
Variance in resulting embeddings

### ISSUE THREAD

**Issue by margokhokhlova** [benedekrozemberczki/graph2vec#17]
Hello!
I tried to calculate your embeddings for my own dataset of 300 graphs. The features are nide degrees as suggested in the paper, I only modified the number of epochs making it 40. 
Let's say I now have embeddings 1, 2 and 3 of the same set of graphs (so graph2vec applied 3 times on the same data).
Then I tried to calculate map@5 for retrieval of the most similar embeddings between the embeddings 1 and 3, 1 and 2, 3 and 2. And I got really bad results, precisely map@5: 0.249222, 0.260222, 0.163278.
I got similar negative results using the dataset provided and default parameters. 
Please, can you comment on that or let me know what I might be doing wrong? 
Thank you!

**Comment by benedekrozemberczki** [comment]
Because of the transductive nature of implicit factorization embeddings from two separate runs are not comparable. You have different initializations and a non-convex optimization problem on which you run SGD. Results would be comparable if: You would have the same initialization, same order of SGD updates, same noise samples drawn.

**Comment by benedekrozemberczki** [comment]
Look at Appendix D of https://arxiv.org/pdf/1706.02216.pdf.

**Comment by AkshatSood** [comment]
> Because of the transductive nature of implicit factorization embeddings from two separate runs are not comparable. You have different initializations and a non-convex optimization problem on which you run SGD. Results would be comparable if: You would have the same initialization, same order of SGD updates, same noise samples drawn.

Is there any way to enforce the same initialization and other conditions in order to achieve comparable results? 

I am asking as I am using Graph2Vec to process some data for a machine learning project. I am a bit concerned about the variations in the results.

**Comment by benedekrozemberczki** [comment]
That is an upstream gensim issue. Take a look there please.
