### ISSUE TITLE
KeyError: "tag 'g_0' not seen in training corpus/invalid"

### ISSUE THREAD

**Issue by malarconb** [benedekrozemberczki/graph2vec#18]
Hi, I'm trying to run the program as indicated in the readme file, from the graph2vec-master directory:
`python src/graph2vec.py`

However, I get the following error:
`Feature extraction started.

100%|████████████████████████████████████████████████████████████████████████| 51/51 [00:05<00:00,  9.59it/s]

Optimization started.

Traceback (most recent call last):
  File "src/graph2vec.py", line 129, in <module>
    main(args)
  File "src/graph2vec.py", line 125, in main
    save_embedding(args.output_path, model, graphs, args.dimensions)
  File "src/graph2vec.py", line 98, in save_embedding
    out.append([int(identifier)] + list(model.docvecs["g_"+identifier]))
  File "c:\users\owner\appdata\local\programs\python\python37\lib\site-packages\gensim\models\keyedvectors.py", line 1600, in __getitem__
    raise KeyError("tag '%s' not seen in training corpus/invalid" % index)
KeyError: "tag 'g_0' not seen in training corpus/invalid"`

I edited the default dataset path (from "/" to "\\") to make it work with Windows. That's all the edit I've done. As you can see, I'm using Python 3.7.  `
Any ideas on what can be causing this error?

**Comment by benedekrozemberczki** [comment]
Not particularly, I am an Ubuntu user.

**Comment by SihamAmarouche** [comment]
I Have same problem, did you get a solution for it ? Thanks

**Comment by malarconb** [comment]
For anyone reading this, I fixed this problem by replacing this line graph2vec.py (99):

`out.append([int(identifier)] + list(model.docvecs["g_"+identifier]))`

with this: 

` out.append([int(identifier)] + list(model.docvecs[int(identifier)]))`

**Comment by benedekrozemberczki** [comment]
Hi there, I would recommend using this: https://github.com/benedekrozemberczki/karateclub/
