### ISSUE TITLE
Question about the outputed embedding

### ISSUE THREAD

**Issue by Andercxt** [benedekrozemberczki/graph2vec#19]
Hi,

I actually find that if I put several completely same graphs into graph2vec, the outputed embeddings are not the same. To be specific, I replicated several 0.json in /dataset and run the training and I found that the outputed embeddings were different.

 I wonder whether this is the correct output.

**Comment by benedekrozemberczki** [comment]
Given the following things it would be surprising to have the same
representations:
- Negative sampling.
- Stochastic gradient descent.
- Random initialization.
- Random shuffling of graph key - feature pairs.

**Comment by Andercxt** [comment]
Ok. Then how can I use the generated embeddings for further usage like clustering if the embeddings will be different even for the same graph.
