### ISSUE TITLE
Small question

### ISSUE THREAD

**Issue by GillesVandewiele** [benedekrozemberczki/graph2vec#2]
Hi Benedek,

First of all, massive amounts of kudos for all the implementations I discovered from you today. Strong work!

Concerning this graph2vec algorithm... At first glance, it seems identical to the rdf2vec algorithm (with the Weisfeiler-Lehman extension), except for the fact that this algorithm cannot deal with named edges (only named nodes). Am I correct, or is there a significant difference that I am currently not seeing?

Also, nice implementation of the WL relabeling! 

Thanks and kind regards,
Gilles

**Comment by benedekrozemberczki** [comment]
Yes, it is the very same idea. People also did similar implicit factorization models based on gspan and anonymous random walk patterns.

**Comment by benedekrozemberczki** [comment]
AWE:

https://arxiv.org/pdf/1805.11921.pdf

The paper with gspan had no public implementation.

**Comment by GillesVandewiele** [comment]
Ye saw that in one of your repositories as well, I'll have a closer look at it! Thanks :).

Maybe one more follow-up question:

In here, Doc2Vec is used, while in RDF2Vec, Word2Vec is used. Is there any reason for using Doc2Vec instead of Word2Vec here?
