### ISSUE TITLE
comparing with original software package and citation

### ISSUE THREAD

**Issue by xiaominUMD** [benedekrozemberczki/graph2vec#21]
Dear author, 
I want to ask, since the software is not the original graph2vec implementation, is this version of implementation generating same result comparing to the original version released by the author of the paper? 
And If I used this work, except that paper, what else can I cite to show that I used your or got some idea from your software?

Thanks

**Comment by benedekrozemberczki** [comment]
About this version:
1. This implementation uses lock-free gradient descent.
2. It runs in parallel in every phase (feature creation and learning). This makes it massively scalable -- You can easily create an embedding for 100 million graphs under an hour on an industry-grade server.
3. The implementation uses the hashing trick to keep the memory footprint of the algorithm linear in the number of edges (this does not affect the runtime.).

This Graph2Vec version is part of the Karate Club package, which can be cited as:

@misc{rozemberczki2020karateclub,
title = {Karate Club: A tool for unsupervised learning on graph structured data.},
author = {Benedek Rozemberczki and Rik Sarkar},
year = {2019},
publisher = {GitHub},
journal = {GitHub repository},
howpublished = {\url{https://github.com/benedekrozemberczki/karateclub}}
}

**Comment by LinglingWang1** [comment]
Hi,
Great! Thanks for the valuable information.

**Comment by xiaominUMD** [comment]
Hi,
Great! Thanks for the valuable information.
