### ISSUE TITLE
json file reading

### ISSUE THREAD

**Issue by DinoBenevento** [benedekrozemberczki/graph2vec#22]
Dear benedekrozemberczki,
I’m a student in Computer Science, from the University of Salerno. 
I’m dealing with your graph2vec implementation after reading the related article, which I found very interesting.
When trying to run your code, I find a little bug. 
Here below you can find the error and my fix.
` parser.add_argument("--input-path",
                        nargs="?",
                        default="../dataset",
               help="Input folder with jsons.")`

`parser.add_argument("--output-path",
                        nargs="?",
                        default="../features/nci2.csv",
               help="Embeddings path.")`
at line 111 of the script graph2vec, the variable `global` was empty, so without the json files of the dataset folder.
`graphs = glob.glob(args.input_path + "*.json")`

I rewrite the code in this way to extract the files into the directory:

`graphs = []`
`pathfilename = args.input_path`
 ` for files in os.listdir(pathfilename):`
        `graphs.append(pathfilename + '/' + files)`

Hope this will help you :D
Given Graph2vec will be a main part of my thesis, don’t you mind if I contact you in case of difficulties?

Kind regards,
Gerardo "Dino" Benevento

**Comment by benedekrozemberczki** [comment]
Hi there Dino,

Are you a windows user?

This package includes a range of Graph2Vec like methods:

https://github.com/benedekrozemberczki/karateclub

Bests,

Benedek

**Comment by benedekrozemberczki** [comment]
Would you reply?

**Comment by benedekrozemberczki** [comment]
Okay. Let us close this for now.
