### ISSUE TITLE
Node Features

### ISSUE THREAD

**Issue by HodaMemar** [benedekrozemberczki/graph2vec#25]
Hi every body
I have a question about node features, as default this features set by node degree, I replace it with a list as below for example:
{"edges": [[1, 2], [1, 3], [1, 4], [2, 3], [2, 4], [3, 4]], "features": {"1": 3, "2": 3, "3": 3, "4": 3}}
replace by
{"edges": [[1, 2], [1, 3], [1, 4], [2, 3], [2, 4], [3, 4]], "features": {"1": [3,1], "2": [3,1], "3": [3,1], "4": [3,1]}}

but I get error : 
RuntimeError: you must first build vocabulary before training the model

How can I use a list as node features in  input of algorithm?
I would be very thankful if you guide me.

**Comment by HodaMemar** [comment]
hello again
in #16 you said "You can create for each feature a separate WL hashing."
cloud you please explain it?
thx

**Comment by benedekrozemberczki** [comment]
Please read the Graph2Vec paper. It means that the original algo is for a
single node feature.
