### ISSUE TITLE
Explanation of params and how to extend to multiple node features

### ISSUE THREAD

**Issue by UCRajkumar** [benedekrozemberczki/graph2vec#26]
I am having a little trouble understanding the following.

1. I don't quite get the intuition behind min_count parameter. How do I properly tune these two parameters, any insight on this would be very  helpful.
2. I'm also having a similar problem with the wl_iterations parameter. Any insight on this param would also be really helpful.
3. Lastly, on a different issue you had mentioned that it's very easy to generalize the node features such that instead of it accepting only one node feature, it could take in multiple. But I'm having trouble implementing this. Pointers to this would also be really helpful!

**Comment by benedekrozemberczki** [comment]
1. If you do not have a min count noisy features will be present. If you set it too high everything will be pruned back (it is controlling the columns included in the factorization process).

2. If you have a too large number of WL iterations each node will have unique features with translates to columns with a single non zero value during the factorization.

3. You can have a nested hash map with node keys, feature name keys and feature values. There was a rejected ICLR submission last year about this idea:
 
https://openreview.net/forum?id=r1xI-gHFDH&noteId=rylK_u2bsH

Benedek
