### ISSUE TITLE
subgrahs

### ISSUE THREAD

**Issue by SihamAmarouche** [benedekrozemberczki/graph2vec#27]
Can I use graph2vec to represent subgraphs(that contain two nodes or three) as vectors then I will cluster these subgraphs to N number clusters using K-means or Dbscan  algorithms Is it a logical process ?

Thanks very much .

**Comment by benedekrozemberczki** [comment]
Could you write something more detailed (step-by-step)?

**Comment by SihamAmarouche** [comment]
I have a big one graph then I used gspan algorithm, FSG or any another algorithm to extract subgraphs from this graph after that I want to cluster these subgraphs using dbscan or k-means and to clustering them(subgraphs) I convert subgraphs to vectors using graph2vec model Is it a logical process I mean can I use graph2vec on subgraphs ? or is there any another suggestions to convert subgraphs to vectors ?

**Comment by benedekrozemberczki** [comment]
It is fine. Just make sure that you reindex them. Other methods in the Karate Club package would work well (e.g. FEATHER). Could you star that repository and hit a follow on github?

**Comment by SihamAmarouche** [comment]
Yes I'm already gave star to this repository and thanks very much for your quick reply .
