### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'dataset\\0'

### ISSUE THREAD

**Issue by networks1** [benedekrozemberczki/graph2vec#28]
Cloned the repository and ran as-is with defaults and given sample data.  Completes feature extraction ok but then getting the following error when it starts the optimization step:

```
Optimization started.

Traceback (most recent call last):
  File "src/graph2vec.py", line 129, in <module>
    main(args)
  File "src/graph2vec.py", line 125, in main
    save_embedding(args.output_path, model, graphs, args.dimensions)
  File "src/graph2vec.py", line 98, in save_embedding
    out.append([int(identifier)] + list(model.docvecs["g_"+identifier]))
ValueError: invalid literal for int() with base 10: 'dataset\\0'
```
Perhaps passing 'dataset\\0' as identifier rather than 0?

**Comment by benedekrozemberczki** [comment]
I would sugges the use of the karateclub implementation. I assume you are a windows user.

**Comment by networks1** [comment]
I am but can switch over to Linux if that’s the issue.  Out of curiosity how does the OS cause this error?

**Comment by benedekrozemberczki** [comment]
The path causes the error.

**Comment by networks1** [comment]
Ah alright.  Thanks for the quick response.
