### ISSUE TITLE
Choosing the right embedding dimension

### ISSUE THREAD

**Issue by ChrisAlthaus** [benedekrozemberczki/graph2vec#29]
Hi,
i am currently trying to figure out what dimension size to choose for my graph database.
Thats because I have relative small graphs with in average 7 (with predicates 14) nodes and 21 edges. 
So with my calculation I come to an extracted_features size of 21 for each input graph, using wl_iteration of 2. 
I'm using following formula for this: 
```
num(extracted_feature) = num(nodes) + num(nodes) * wl_iterations 
```
So this means in words of doc2vec, that each document has 21 words. Am i right in this point?
Because that seems a bit low to me, i wonder which dimension size to choose. Which dimension size should I use for this setup? A dimension size of 128 for me seems too high.

Greetings and thanks for this great work,
Christian

**Comment by benedekrozemberczki** [comment]
Dear Chris,

The procedure factorizes (implicitly) a graph - WL feature matrix (which is sparse). The number of rows in this matrix is the number of graphs and the number of columns is the number of unique WL features for all of the graphs. The number of dimensions is the number of basis vectors used for the factorization. You can look at the Graph2Vec paper for more details. I would recommend the use of the Karate Club implementation of Graph2Vec.  

Please do not forget to star the repos.

Bests,

Benedek
