### ISSUE TITLE
Questions for some use cases

### ISSUE THREAD

**Issue by john-wick-ksg** [benedekrozemberczki/graph2vec#3]
Hi, thanks for the great code.

Let me ask the followings.
I want to use multiple dimension vectors for the features.
For example, I want to input like this:
`{"edges":[[0, 1]], "features": {"0": ["0.1", "0.1"], "1": ["0.0", "0.1"]}`
Can we do it?

One more thing.
Can we save the model and use it for another input data which is not used for training and output the result CSV for it?

Best regards.

**Comment by benedekrozemberczki** [comment]
1. This model only works when You have a single string feature. However, You can generalize it to multi feature cases (for string/categorical features). If You extract WL node features for each node feature separately (You can rewrite it easily) -- each string feature must get a "feature_x_" prefix. The feature extraction and optimization runtime will be exactly multiplied by the number of features (assuming no down sampling). May I ask what is the exact use case?

2. Yes you can make it work for an inductive setting if all of the node features have been seen up to that point.

**Comment by john-wick-ksg** [comment]
Thanks for your reply.

1. I have no idea how to modify for now but will try. My use case is programming language source code structures. Each node is a parsed token.

2. Got it, will try this as well.

**Comment by benedekrozemberczki** [comment]
1. Are you writing a paper?
