### ISSUE TITLE
Different number node and edge

### ISSUE THREAD

**Issue by danhtrancao** [benedekrozemberczki/graph2vec#30]
Hi, 
I'm facing the problems about number of nodes and edges, I have 7 nodes but just have 6 edges. I'm facing the error: joblib.externals.loky.process_executor._RemoteTraceback: self.do_recursions(). How to implement graph2vec?

**Comment by benedekrozemberczki** [comment]
You need a list of graphs. What is your exact ML problem?

**Comment by benedekrozemberczki** [comment]
Did you read the Graph2Vec paper?

**Comment by danhtrancao** [comment]
I have already read it and run source with only file json and successful generation the csv file. I changed the dataset in json file by my dataset with {"edges": [[0, 1], [0, 2], [1, 3], [1, 4], [2, 5], [2, 6]], "features": {"0": "1", "1": "1", "2": "3", "3": "3", "4": "3", "5": "3"}}. It seems not correct between number of edges and nodes so the error message appear. I count the number of nodes is 7 and edges is 6. I think this is cause error.

**Comment by danhtrancao** [comment]
I got the idea, thanks!

**Comment by benedekrozemberczki** [comment]
Your problem is that you have 7 nodes (0,1,2,3,4,5,6) and the node feature dictionary has 6 entries.
