### ISSUE TITLE
Visualisation of graph2vec embeddings in a network

### ISSUE THREAD

**Issue by NM4455** [benedekrozemberczki/graph2vec#35]
Hello,

Is it possible to see the network resulting from the DeepWalk embedding of a graph2vec dataset?

The aim is to bring together the nodes that are most connected in order to ease their vizualisation.

Many thanks in advance,

Nicolas

**Comment by benedekrozemberczki** [comment]
I do not get the question.

**Comment by NM4455** [comment]
Well, I have a undirected network of hundred of nodes & vertices and I would like to "organize it" according to the embeddings thanks to a DeepWalk. It would group de most connected notes (=clustering) and isolate the less connected ones.

I've seen the examples in the KarateClub page, but there is no visualization of the result obtained with the embeddings.

Note: I'm not very familiar with graphs, sorry if my questions sound absurds.

**Comment by benedekrozemberczki** [comment]
You can plot a 2D DeepWalk embedding, people do it commonly.

**Comment by benedekrozemberczki** [comment]
Can you star the repositories and follow me?

**Comment by NM4455** [comment]
Thanks.

Yes of course.
