### ISSUE TITLE
Question about embeddings 

### ISSUE THREAD

**Issue by maurovit** [benedekrozemberczki/graph2vec#36]
Hello,
My goal is to use this model to obtain the graphs embeddings and use these to create a training set for another machine learning model. Is this correct? However, after training graph2vec on my custom dataset, how do I get the embeddings of an previously unseen graphs, i.e. a graph that are not in the training set?

**Comment by benedekrozemberczki** [comment]
You can infer those if you write the appropriate function. I would
recommend using the FEATHER method in Karate Club, which is inductive by
default - you can fit it to new graphs.

**Comment by maurovit** [comment]
First of all, thank you for your quick reply. 
I read the code for the FeatherGraph class in Karateclub, should I use this one? 
Anyway, I see that the two methods used are fit for training and get_embeddings to get the embeddings of the training data. If I have a new graph, do I have to re-run the fit method on the entire updated dataset or can I just infer the embeddings of that graph with another method?

**Comment by benedekrozemberczki** [comment]
First of all, could you star the two repos and follow me on github?

Yes, so the method can output new representations for a new set of graphs.
E.g. this would operate on the same embedding space:

graphs_1 = Set of graphs
graphs_2  = Other set of graphs

model = FeatherGraph()

model.fit(graphs_1)
X_1 = model_get_embedding()

model.fit(graphs_2)
X_2 = model_get_embedding()

This creates embeddings in the same space!

**Comment by maurovit** [comment]
Thank you a lot, very deserved stars and follow. Congratulations for your works!

**Comment by sdoradoa** [comment]
Hi,

I have the same question. I tried to use Feather but I am not getting good results so I would like to keep using Graph2Vec. The sequence I would like to follow is getting the embedding for the training set and then predict a vector for a new graph without retraining the model. Is this possible?

Thank you for your help and knowledge.
