### ISSUE TITLE
Input JSON

### ISSUE THREAD

**Issue by nathanhu3** [benedekrozemberczki/graph2vec#37]
I was having trouble running the script when the input dictionaries had no 'feature' key. Running the script would return this error:

`'DegreeView' object has no attribute 'items'`

I'm not the most experienced programmer so I could be wrong here but I think in networkx 2.4 `networkx.Graph.degree` returns an iterable and not a dict. So in line 72 of `graph2vec.py`, I had to consider the case when `features` was an iterable so I changed `features.items()` to `list(features)`. And this worked for input dictionaries with no feature key so it now looks like:
```
if "features" in data.keys():
    features = data["features"]
    features = {int(k): v for k, v in features.items()}
else:
    features = nx.degree(graph)
    features = {int(k): v for k, v in list(features)}
```
Maybe I'm completely wrong but just in case anyone else had the same issue this might help since this worked for me.

https://github.com/benedekrozemberczki/graph2vec/blob/a2001d0d6595d082635f2e75fa7275ad0690ff70/src/graph2vec.py#L72

**Comment by benedekrozemberczki** [comment]
Do you want to open a PR?
