### ISSUE TITLE
[Question] Add PyPi package

### ISSUE THREAD

**Issue by rodrigo-arenas** [benedekrozemberczki/graph2vec#41]
Hi, I find this package very interesting. 
I was wondering if this could be added as a package in PyPI so that it can be easily installed/used inside larger projects.

Greetings

**Comment by benedekrozemberczki** [comment]
The karateclub library provides a PyPI installable graph2vec.

**Comment by rodrigo-arenas** [comment]
Thanks! I'll check it out
