### ISSUE TITLE
RuntimeError: you must first build vocabulary before training the model

### ISSUE THREAD

**Issue by juliolopes98** [benedekrozemberczki/graph2vec#46]
Hello! I was trying to use my own dataset, with the format that you give on the exmaple. But by running the code, i get the following error: "RuntimeError: you must first build vocabulary before training the model". Here I show a sample of the dataset.

{"edges": [[0, 16], [0, 14], [1, 2], [1, 2], [2, 1], [2, 16], [3, 4], [3, 2], [4, 8], [4, 3], [5, 1], [5, 17], [6, 7], [6, 11], [7, 11], [7, 6], [8, 4], [8, 11], [9, 12], [9, 13], [10, 13], [10, 9], [11, 7], [11, 8], [12, 9], [12, 13], [13, 10], [13, 12], [14, 16], [14, 0], [15, 0], [15, 14], [16, 0], [16, 0], [17, 15], [17, 0]], "features": {"0": 4, "1": 5, "2": 28, "3": 28, "4": 28, "5": 37, "6": 40, "7": 48, "8": 28, "9": 40, "10": 28, "11": 41, "12": 32, "13": 40, "14": 11, "15": 32, "16": 28, "17": 36, "18": 20, "19": 50, "20": 23, "21": 56, "22": 11, "23": 36, "24": 20, "25": 48, "26": 23, "27": 48, "28": 4, "29": 5, "30": 11, "31": 12, "32": 4, "33": 4, "34": 14, "35": 20}}

**Comment by smith-co** [comment]
@juliolopes98 have you solved the issue?
