### ISSUE TITLE
Graph2vec for graph similarity learning

### ISSUE THREAD

**Issue by smith-co** [benedekrozemberczki/graph2vec#47]
I am thinking to use Graph2vec for learning graph similarity learning.

Given two graphs, I am thinking to get embeddings of the two graphs and then take the cosine similarity of the two graphs.

May graphs would have around 5000 nodes and 4000 edges.

Is Graph2vec a good fit for this task?

**Comment by benedekrozemberczki** [comment]
Dear @smith-co,

Could you star the repo first?

Yes it is! I would recommend using the Karateclub implementation!

https://github.com/benedekrozemberczki/karateclub

Bests,

Benedek

**Comment by smith-co** [comment]
@benedekrozemberczki of course - added star to the repo :-)

I am looking into the Karateclub repo. Can you please point me how to create the API to create graphs for Karateclub?

**Comment by smith-co** [comment]
@benedekrozemberczki do you have an example where you build a graph from scratch i.e. create nodes and then add edges?
