### ISSUE TITLE
graph encoding

### ISSUE THREAD

**Issue by arademaker** [benedekrozemberczki/graph2vec#48]
What are the features? Can a node have more than one feature (string value)? Can edges have features? I am trying to encode semantic structures such as 

http://delph-in.github.io/delphin-viz/demo/#input=I%20bought%20a%20book%20yesterday.&count=1&grammar=erg2018-uw&dmrs=true

Does it make sense? At a minimum, nodes have labels, edges have labels. Nodes can also have extra information attached to it (move the mouse over the nodes to see some examples). Can I encode that in graph2vec?

**Comment by smith-co** [comment]
@arademaker I asked the same question here https://github.com/benedekrozemberczki/karateclub/issues/101

**Comment by arademaker** [comment]
Let us hope for some answers! ;-)

**Comment by smith-co** [comment]
@arademaker probably you can raise the issue in the Karate Club repo as that's the repo that should be used.

**Comment by benedekrozemberczki** [comment]
Hi there,

I would suggest using the KarateClub library. In Graph2Vec each node can have a single string feature. If you have continuous features these can be encoded with log binning and integer rounding. The Karate Club Data loaders are great examples in my opinion. Can you star these repos and hit follow?

Reading the Graph2Vec paper is also helpful to wrap your head around the concept.

Bests,

Benedek

**Comment by srinathmadasu76** [comment]
How to add more than one string features to the nodes? Anyone can help?

**Comment by srinathmadasu76** [comment]
Is it even possible to add more features?
