### ISSUE TITLE
error while running in windows

### ISSUE THREAD

**Issue by logomanwolf** [benedekrozemberczki/graph2vec#5]
hello!
When I run "python src/graph2vec",there is some errors 
![1](https://user-images.githubusercontent.com/31181377/52950051-f772b680-33b8-11e9-8b6d-3f232765681b.JPG)
And then I set breakpoints like this 
![2](https://user-images.githubusercontent.com/31181377/52950579-8fbd6b00-33ba-11e9-863f-f40778744e33.JPG)
And I found 
`f="./dataset\\0.json"`  and  ` identifier="dataset\\0"`. That's why int(indentifier) is not correct.  
I want to know what `identifier` should be if program run in a correct way(or in linux)

**Comment by benedekrozemberczki** [comment]
The graph names should be integers. See readme.  It was tested on Ubuntu.

**Comment by logomanwolf** [comment]
Thank you so much for replying to me so quickly.
Actually, I hadn't changed anything at all and the graph names had been integers. I think it was the difference OS that caused the problem. I changed the code to this and it worked.
![1](https://user-images.githubusercontent.com/31181377/52983535-88cc4200-3426-11e9-89be-b117d484f121.JPG)
Do you think the changing in accordance with your idea?

**Comment by benedekrozemberczki** [comment]
Seems fine. Can You run it now properly?

**Comment by logomanwolf** [comment]
Yes.It seemed alright.Thank you so much.
