### ISSUE TITLE
Can I use multiple features of a particular node? 

### ISSUE THREAD

**Issue by bahmedraaz** [benedekrozemberczki/graph2vec#50]
For example, in the example dataset, the features in the graph looks like this, {"features": {"0": "1", "1": "1", "2": "1", "3": "1"}.
If node 0 has multiple features, can I use those in a list? For example, as follows...
{"features": {"0": [1,0.1, 3, 5, 1.2], "1": [0.7, 0.8], "2": "1", "3": "1"}.

I tweaked the graph data like this but didn't notice any change in the graph encoding. Can you please help me how can I use multiple features of nodes during the embedding?

**Comment by benedekrozemberczki** [comment]
Recommend using the FEATHER algorithm.
