### ISSUE TITLE
Graph2vec infer

### ISSUE THREAD

**Issue by Mats29** [benedekrozemberczki/graph2vec#52]
Hi, I am trying to use the infer method to test my graph2vec embedding without retraining the model. I follow these steps

graphs_train = list of networkx graphs
graphs_test = list of networkx graphs
g2v_emb = g2v.Graph2Vec()
g2v_emb.fit(graphs_train)
test_emb = g2v_emb.infer(graphs_test)

However, this returns a list that looks like this: ['9', '595be5e4bb7167f35a2878342bed1787', '00129eb2ff1730f9d0db0e5e3ecb7059', '5', '92dd168e872bef807dc1617ddd3f4bd3', ...]. Any idea of where I am going wrong here?

Also, thank you for this repository, this code has been very helpful!

**Comment by benedekrozemberczki** [comment]
Can you use the karateclub implementation @Mats29 ?
